simbion_auth/urls.py
from django.conf.urls import url

from.views import login, logout, register

app_name = 'simbion_auth'

urlpatterns = [
  url(r'^login/$', login, name='login'),
  url(r'^logout/$', logout, name='logout'),
  url(r'^register/$', register, name='register'),
]

simbion_beasiswa/urls.py
from django.conf.urls import url

from.views import index, new, new_beasiswa_paket, add_new_beasiswa, lihat

app_name = 'simbion_beasiswa'

urlpatterns = [
  url(r'^$', index, name='index'),
  url(r'^new$', new, name='new'),
  url(r'^new-paket$', new_beasiswa_paket, name='new_beasiswa_paket'),
  url(r'^add-beasiswa$', add_new_beasiswa, name='add_new_beasiswa'),
  url(r'^lihat$', lihat, name='lihat'),
]

tk4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

import simbion_auth.urls as simbion_auth
import simbion_beasiswa.urls as simbion_beasiswa

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^auth/', include(simbion_auth, namespace='simbion_auth')),
    url(r'^', include(simbion_beasiswa, namespace='simbion_beasiswa'))
]

simbion_beasiswa/models.py
from django.db import models

from simbion_auth.models import Pengguna, Donatur

# Create your models here.
class Skema_Beasiswa(models.Model):
  kode = models.IntegerField('kode', unique=True)
  nama = models.CharField('nama', max_length=50)
  jenis = models.CharField('jenis', max_length=20)
  deskripsi = models.CharField('deskripsi', max_length=50)
  nomor_identitas_donatur = models.ForeignKey(Donatur, to_field='nomor_identitas', on_delete=models.CASCADE)

class Syarat_Beasiswa(models.Model):
  syarat = models.CharField('syarat', max_length=50)
  kode_beasiswa = models.ForeignKey(Skema_Beasiswa, to_field='kode', on_delete=models.CASCADE)

class Skema_Beasiswa_Aktif(models.Model):
  no_urut = models.IntegerField('no_urut')
  tgl_mulai_pendaftaran = models.DateField()
  tgl_tutup_pendaftaran = models.DateField()
  periode_penerimaan = models.CharField('periode_penerimaan', max_length=50, null=True)
  status = models.CharField('status', max_length=20, null=True)
  jumlah_pendaftar = models.IntegerField(null=True)
  kode_skema_beasiswa = models.ForeignKey(Skema_Beasiswa, to_field='kode', on_delete=models.CASCADE)

simbion_beasiswa/views.py
from django.shortcuts import render, redirect
from .models import Skema_Beasiswa, Syarat_Beasiswa, Skema_Beasiswa_Aktif
from simbion_auth.models import Donatur
# Create your views here.
response = {}
def index(request):
  response['role'] = request.session['role'] if 'role' in request.session else 'guest'
  return render(request, 'home/index.html', response)

def new(request):
  response['role'] = request.session['role'] if 'role' in request.session else 'guest'
  if response['role'] != 'donatur':
    return redirect('simbion_beasiswa:index')
  return render(request, 'home/membuat_beasiswa_baru.html')

def new_beasiswa_paket(request):
  response['role'] = request.session['role'] if 'role' in request.session else 'guest'
  if response['role'] != 'donatur':
    return redirect('simbion_beasiswa:index')

  if request.method == 'POST':
    donatur = Donatur.objects.get(username=request.session['user'])
    skema_beasiswa = Skema_Beasiswa.objects.create(
      kode = request.POST['kode'],
      nama = request.POST['nama'],
      jenis = request.POST['jenis'],
      deskripsi = request.POST['deskripsi'],
      nomor_identitas_donatur = donatur
    )
    syarat = Syarat_Beasiswa.objects.create(
      syarat = request.POST['syarat'],
      kode_beasiswa = skema_beasiswa
    )
    return redirect('simbion_beasiswa:index')
  elif request.method == 'GET':
    return render(request, 'home/membuat_paket_beasiswa.html')

def add_new_beasiswa(request):
  response['role'] = request.session['role'] if 'role' in request.session else 'guest'
  if response['role'] != 'donatur':
    return redirect('simbion_beasiswa:index')

  response['kodes'] = Skema_Beasiswa.objects.all()

  if request.method == 'POST':
    beasiswa = Skema_Beasiswa.objects.get(kode=request.POST['kode'])
    skema_beasiswa_aktif = Skema_Beasiswa_Aktif.objects.create(
      no_urut = request.POST['nomor'],
      tgl_mulai_pendaftaran = request.POST['mulai'],
      tgl_tutup_pendaftaran = request.POST['tutup'],
      kode_skema_beasiswa = beasiswa,
    )
    return redirect('simbion_beasiswa:index')
  elif request.method == 'GET':
    return render(request, 'home/tambah_beasiswa_baru.html', response)

def lihat(request):
  response['role'] = request.session['role'] if 'role' in request.session else 'guest'
  
  if response['role'] == 'guest':
    return redirect('/')

  response['info_beasiswa'] = Skema_Beasiswa_Aktif.objects.all()

  return render(request, 'home/lihat_beasiswa.html', response)

simbion_beasiswa/templates/home/index.html
<html>
  {% if role == "mahasiswa" %}
    <p><a href="{% url 'simbion_beasiswa:lihat' %}">Lihat Beasiswa</a></p>
    <p><a href="{% url 'simbion_auth:logout' %}">Logout</a></p>
  {% elif role == "donatur" %}
    <p><a href="{% url 'simbion_beasiswa:lihat' %}">Lihat Beasiswa</a></p>
    <p><a href="{% url 'simbion_beasiswa:new' %}">Membuat Beasiswa Baru</a></p>
    <p><a href="{% url 'simbion_auth:logout' %}">Logout</a></p>
  {% else %}
    <p><a href="{% url 'simbion_auth:login' %}">Login</a></p>
    <p><a href="{% url 'simbion_auth:register' %}">Register</a></p>
  {% endif %}
</html>

simbion_beasiswa/templates/home/lihat_beasiswa.html
<!DOCTYPE html>
<html>

<body>

    <h2>DAFTAR BEASISWA</h2>

    <table style="width:100%">
        <tr>
            <th>Nomor Urut</th>
            <th>Waktu Tutup Pendaftaran</th>
            <th>Total Mahasiswa</th>
        </tr>
        {% for data in info_beasiswa %}
        <tr>
            <th>{{data.no_urut}}</th>
            <th>{{data.tgl_tutup_pendaftaran}}</th>
            <th>0</th>
        </tr>
        {% endfor %}
    </table>

</body>

</html>

simbion_beasiswa/templates/home/membuat_beasiswa_baru.html
<html>
  <p><a href="{% url 'simbion_beasiswa:new_beasiswa_paket' %}">Membuat Paket Beasiswa Baru</a></p>
  <p><a href="{% url 'simbion_beasiswa:add_new_beasiswa' %}">Menambahkan Beasiswa dari Paket</a></p>
</html>

simbion_beasiswa/templates/home/membuat_paket_beasiswa.html
<html>
  <form action="{% url 'simbion_beasiswa:new_beasiswa_paket' %}" method="POST">
    {% csrf_token %}
    <p>
      <label for="kode">Kode</label>
      <input type="text" id="kode" name="kode">
    </p>
    <p>
      <label for="nama">Nama Paket Beasiswa</label>
      <input type="text" id="nama" name="nama">
    </p>
    <p>
      <label for="jenis">Jenis Paket Beasiswa</label>
      <input type="text" id="jenis" name="jenis">
    </p>
    <p>
      <label for="deskripsi">Deskripsi</label>
      <input type="text" id="deskripsi" name="deskripsi">
    </p>
    <p>
      <label for="syarat">Syarat Beasiswa</label>
      <input type="text" id="syarat" name="syarat">
    </p>
    <input type="submit">
  </form>
</html>

simbion_beasiswa/templates/home/tambah_beasiswa_baru.html
<html>
  <form action="{% url 'simbion_beasiswa:add_new_beasiswa' %}" method="POST">
    {% csrf_token %}
    <p>
      <select name="kode" id="kode" autocomplete="off" required="">
        <option value="" selected disabled>Kode</option>
        {% for kode in kodes %}
          <option value="{{kode.kode}}">{{kode.kode}}</option>
        {% endfor %}
      </select>
    </p>
    <p>
      <label for="nomor">Nomor Urut</label>
      <input type="text" id="nomor" name="nomor">
    </p>
    <p>
      <label for="mulai">Tanggal Mulai Pendaftaran</label>
      <input type="date" id="mulai" name="mulai">
    </p>
    <p>
      <label for="tutup">Tanggal Tutup Pendaftaran</label>
      <input type="date" id="tutup" name="tutup">
    </p>
    <input type="submit">
  </form>
</html>